version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Mapeia a porta 80 do container para a porta 3000 do host
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
